query GetServiceDeployments($serviceId: String!) {
  deployments: getServiceDeployments(serviceId: $serviceId) {
    id
    serviceId
    provider
    image
    internalName
    replicas
    status
    cpuLimit
    memoryLimit

    createdAt
    updatedAt
  }
}
