subscription ServiceDeployments($serviceId: String!) {
  payload: serviceDeployments(serviceId: $serviceId) {
    event_type
    deployment {
      id
      serviceId
      provider
      image
      internalName
      replicas
      status
      cpuLimit
      memoryLimit
      createdAt
      updatedAt
    }
  }
}
