name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and push the Docker image
      run: |
        docker buildx build --platform linux/amd64 --provenance false --push -t registry.digitalocean.com/acceleratio/core-backend:latest ./packages/core-nest &
        docker buildx build --platform linux/amd64 --provenance false --push -t registry.digitalocean.com/acceleratio/builder:latest ./packages/builder &
        docker buildx build --platform linux/amd64 --provenance false --build-arg NEXT_PUBLIC_API_URL=https://portal.acceleratio.dev/api --push -t registry.digitalocean.com/acceleratio/core-frontend:latest ./packages/dashboard-web-next &
        wait
